### ISSUE TITLE
Nao foi possivel fazer o replace de ARN

### ISSUE THREAD

**Issue by marciofilhozup** [GuillaumeFalourd/replace-values-action#1]
Como o arn possui :: , por exemplo "arn:aws:iam::***:role/***" o split nao é realizado corretamente.
Nesse caso do arn o resultado do replace desse arn com " (aspas duplas )  ficaria "arn

**Comment by GuillaumeFalourd** [comment]
> Como o arn possui :: , por exemplo "arn:aws:iam::_**:role/**_" o split nao é realizado corretamente. Nesse caso do arn o resultado do replace desse arn com " (aspas duplas ) ficaria "arn

Vou ver se teria como fazer o split em bash para no máximo 2 elementos, senão talvez seria necessário mudar o uso de `::` para fazer o split.

**Comment by GuillaumeFalourd** [comment]
Resolvido através da tag `v1.1` (substituindo `::` por `>>`)
